language: objective-c
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - curl https://github.com/appcelerator-modules/ci/blob/master/travis/install.sh | source
    
before_script:
    - cd $MODULE_ROOT
script: 
    - if [ -d "$MODULE_ROOT/ios/" ]; then
    -   cd $MODULE_ROOT/ios/
    -   ./build.py
    - fi

    - if [ -d "$MODULE_ROOT/android/" ]; then
    -   cd $MODULE_ROOT/android/
    -   cp $MODULE_ROOT/build.properties build.properties
    -   ant clean
    -   ant
    - fi
