language: objective-c
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - source ./scripts/install.sh
    
before_script:
    - cd $MODULE_ROOT
script: 
    - echo $PATH
    - cat /Users/travis/build.sh
    - cd $MODULE_ROOT/ios/
    - ./build.py
    
    - cd $MODULE_ROOT/android/
    - ant clean
    - ant
