language: objective-c
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - source ./scripts/install.sh
    
before_script:
    - cd $MODULE_ROOT
script: 
    - cd $MODULE_ROOT/ios/
    - ./build.py
    
    - cd $MODULE_ROOT/android/
    - ant clean
    - ant -Dtitanium.platform="/Library/Application Support/Titanium/mobilesdk/osx/2.1.3.GA/android" -Dandroid.platform="/Library/Application Support/Titanium/sdks/android-sdk-macosx/platforms/android-10" -Dgoogle.apis="/Library/Application Support/Titanium/sdks/android-sdk-macosx/add-ons/addon-google_apis-google-10"
