language: objective-c
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - source ./scripts/install.sh
    
before_script:
    - cd $MODULE_ROOT
script: 
    - cd $MODULE_ROOT/ios/
    - ./build.py
    
    - cd $MODULE_ROOT/android/
    - cp $MODULE_ROOT/scripts/build.properties build.properties
    - ant clean
    - ant
