language: objective-c
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - curl https://github.com/appcelerator-modules/ci/blob/master/travis/install.sh | source
    
before_script:
    - cd $MODULE_ROOT
script: 
    - cd $MODULE_ROOT/ios/
    - ./build.py
    
    - cd $MODULE_ROOT/android/
    - cp $MODULE_ROOT/build.properties build.properties
    - ant clean
    - ant
