language: objective-c
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - source ./scripts/install.sh
    - which brew
    - which port
    
before_script:
    - cd $MODULE_ROOT
script: 
    - cd $MODULE_ROOT/ios/
    - ./build.py
    
    - cd $MODULE_ROOT/android/
    - ant clean
    - ant
